const initialState = {
    user: "",
    SFCategory: [],
    SFData: [{ word: "Development", bnWord: "উন্নতি" }],
    VBCategory: [],
    VBData: [{ word: "Development", bnWord: "উন্নতি" }],
    GrammarCategory: [],
    GrammarData: [],
    ParagraphCategory: [],
    ParagraphData: [],
    CompositionCategory: [],
    CompositionData: [],
    DialogueCategory: [],
    DialogueData: [],
    CVCategory: [],
    CVData: [],
    ApplicationCategory: [],
    ApplicationData: [],
    LetterCategory: [],
    LetterData: [],
    StoryCategory: [],
    StoryData: [],
    GraphCategory: [],
    GraphData: [],
    EmailCategory: [],
    EmailData: [],
    loading_status: "loading"
};

export default initialState;